/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-mongodb:2.7.5")
    api("org.springframework.boot:spring-boot-starter-web:2.7.5")
    api("org.projectlombok:lombok:1.18.24")
    api("org.springframework.boot:spring-boot-starter-thymeleaf:2.7.5")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.21")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.5")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.21")
}

group = "com.bookStore"
version = "0.0.1-SNAPSHOT"
description = "bookStore"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
